### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by shakdwipeea** [one100solutions/website-viands#1]
Add video folder to gitignore and serve it via cdn

**Comment by shakdwipeea** [comment]
Also make this change in master. Write now cloning the repo downloads a lot of data, try to minimize it

**Comment by ghost** [comment]
Serving video through cdn is done. 
Do you want me to make any changes in master for now? Or let it be as it is?

**Comment by shakdwipeea** [comment]
We will make changes in the master when website is ready to be launced. 
This issue is I guess sorted now /
